### ISSUE TITLE
Types serialization / deserialization

### ISSUE THREAD

**Issue by zdm** [tobyink/p5-type-tiny#19] opened 2015-03-05 02:08 UTC
I can't find proper way to serialize types.
I am trying to use "display_name" for serialization and eval for deserialization. But this works not for all parametrized types. 

For example, StrMatch [qr/.../] can't be evaluated correctly.

Is it possible to add additional attribute, for example, serialize => sub {...}, so each type can correctly serialize yourself.

And additional Type::Tiny constructor method, than can create object from serialized value.

**Comment by tobyink** [comment] 2017-05-18 09:12
Duplicate of https://rt.cpan.org/Ticket/Display.html?id=102639

**Closed by tobyink** 2017-05-18 09:12 UTC
